# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: false
check_commit_message: false
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: false
deploy_client_to_rubygems: false
deploy_daily_client_to_pypi: false
deploy_daily_client_to_rubygems: false
deploy_to_pypi: false
docker_fixtures: false
docs_test: false
plugin_app_label: rpm
plugin_camel: PulpRpmPrerequisites
plugin_camel_short: Rpm
plugin_caps: PULP_RPM_PREREQUISITES
plugin_caps_short: RPM
plugin_dash: pulp-rpm-prerequisites
plugin_dash_short: rpm
plugin_name: pulp_rpm_prerequisites
plugin_snake: pulp_rpm_prerequisites
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pydocstyle: false
pypi_username: null
stable_branch: null
test_bindings: false
test_performance: false
test_s3: false
travis_addtl_services: []
travis_notifications: null

