---
name: Pulp PR
on: pull_request
jobs:
  compact_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # For PRs, to save GHA resources, only run on 1 python version
      matrix:
        include:
          - env:
              TEST_TYPE: release-static
            python: "2.7"
          - env:
              TEST_TYPE: source-static
            python: "2.7"
          - env:
              TEST_TYPE: release-dynamic
            python: "3.6"
          - env:
              TEST_TYPE: source-dynamic
            python: "3.6"
          - env:
              TEST_TYPE: release-upgrade
            python: "3.7"
          - env:
              TEST_TYPE: source-upgrade
            python: 3.7
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install yq
        run: |
          sudo add-apt-repository --yes ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox requests
      - name: Check commit message
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
        run: |
          for sha in $(curl $GITHUB_CONTEXT | jq '.[].sha' | sed 's/"//g')
          do
            python .github/validate_commit_message.py $sha
            VALUE=$?
            if [ "$VALUE" -gt 0 ]; then
              exit $VALUE
            fi
          done
        shell: bash
      - name: Before Install
        run: .github/before_install.sh
      - name: Set tox env for python 27
        if: matrix.python == '2.7'
        run: echo "::set-env name=TOXENV::py27-${{ matrix.env.TEST_TYPE }}"
      - name: Set tox env for python 36
        if: matrix.python == '3.6'
        run: echo "::set-env name=TOXENV::py36-${{ matrix.env.TEST_TYPE }}"
      - name: Set tox env for python 37
        if: matrix.python == '3.7'
        run: echo "::set-env name=TOXENV::py37-${{ matrix.env.TEST_TYPE }}"
      - name: Pulling images for upgrade
        if: matrix.env.TEST_TYPE == 'release-upgrade' || matrix.env.TEST_TYPE == 'source-upgrade'
        run: |
          docker pull quay.io/pulp/pulp_rpm-ci-c7:3.1.0
          docker pull quay.io/pulp/pulp_rpm-ci-f31:3.1.0
      - name: Run tox
        run: ./.pulp_installer_tox.sh
        env:
          TEST_TYPE: ${{ matrix.env.TEST_TYPE }}
        shell: bash
